### ISSUE TITLE
$!.pending

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#1214]
Migrated from [rt.perl.org#68320](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=68320) (status was 'open')

Searchable as RT68320$

**Comment by JJ** [comment]
if this ticket is addressed/closed it would mean closing something that is 11 years old...

**Comment by JJ** [comment]
I would say this no longer holds. EVAL (not `eval`) throw inmediately, and `.pending` is implemented. So I would say that this issue is no longer relevant.

**Comment by AlexDaniel** [comment]
But what does it mean? Does it mean that tests for .pending should be removed?

**Comment by AlexDaniel** [comment]
And if `.pending` was implemented, then what's the meaning of that comment from 2016?

**Comment by JJ** [comment]
Well, it means that the original issue:

> Method 'pending' not found for invocant of class 'Exception'

no longer holds. The way I see it, @skids' comment raises a totally different issue.

**Comment by JJ** [comment]
Closing this again, since the issue as stated has been solved.
