### ISSUE TITLE
LTA error message when referring to a non-existent class whose  name contains a '::' in Rakudo

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#1453]
Migrated from [rt.perl.org#71482](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=71482) (status was 'open')

Searchable as RT71482$

**Comment by JJ** [comment]
The error is now much more awesome:

```
Could not find symbol '&B' in 'A'
  in block <unit> at <unknown file> line 1
```

Still, it needs someone to understand that namespaces are automatically created this way, and it still assumes (I guess probably due to the lack of sigils) that it's a routine. Not clear if this is a local optimum or it could be awesomer...

**Comment by masak** [comment]
I'd say the original problem is way beyond fixed. Closing.
