### ISSUE TITLE
Long running unclosed quotes trigger unhelpful message

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#1808]
Migrated from [rt.perl.org#75592](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=75592) (status was 'open')

Searchable as RT75592$

**Comment by JJ** [comment]
> ### From @AlexDaniel
> 
> I'm slightly confused by this ticket… isn't it resolved now? Nowadays you get an error message like this​:
> 
> Unable to parse expression in single quotes; couldn't find final "'" (corresponding starter was at line 2)
> 
> So while it blows up at the end of the file, it still mentions where the quote started. Sooo… fixed? I'm struggling to understand what these code samples were supposed to demonstrate.

Fixed, I guess. Also, eval is how EVAL.

**Comment by AlexDaniel** [comment]
OK! Maybe there are other cases when it doesn't print a nice error message, in which case please file a bug report. But IIRC my fix resolved most of the issues.
