### ISSUE TITLE
Multi method in class implementing stubbed method in role causes bogus "must be implemented" error in Rakudo

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#2901]
Migrated from [rt.perl.org#114930](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=114930) (status was 'new')

Searchable as RT114930$

**Comment by usev6** [comment]
This seems to work nowadays:
```
$ m 'role R { method m (*@a) { ... } }; class C does R { multi method m (*@a) {} }; say "alive"'
alive
$ ./rakudo-m -e 'role R { method m (*@a) { ... } }; class C does R { multi method m (*@a) { "OHAI".say } }; my C $c .= new(); $c.m(3)'
OHAI
```

According to [bisectable6](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2023-02-19#l91) this has been fixed back in 2018 with https://github.com/rakudo/rakudo/commit/fd5d5bdfb9. (That commit mentions a more recent Rakudo issue (which looks very similar to this old issue): https://github.com/rakudo/rakudo/issues/2386.)

Probably it would make sense to add a test to roast for this issue. Tagging "rtestneeded"

**Comment by usev6** [comment]
We have a test now, added with https://github.com/Raku/roast/commit/1c7224ada5. (With the help of (committable6)[https://colabti.org/irclogger/irclogger_log/raku-dev?date=2023-02-20#l17] I figured out that the slurpy parameter is not relevant for the bug, so I left it out.)

I'm closing this issue as resolved.
