### ISSUE TITLE
junctions reporting true & false, not collapsing

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#2917]
Migrated from [rt.perl.org#115270](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=115270) (status was 'open')

Searchable as RT115270$

**Comment by usev6** [comment]
Nowadays this works on the JVM backend, too:
```
> my \a = any set <1 2 3>;
any(Set(1 2 3))
> say 1 ~~ a
False
> 
```

Test added with https://github.com/rakudo/rakudo/commit/45e8e8d987, I'm closing this issue.
