### ISSUE TITLE
LTA error message when referring to nonexistent symbol in constant declaration

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3405]
Migrated from [rt.perl.org#122022](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=122022) (status was 'open')

Searchable as RT122022$

**Comment by usev6** [comment]
This has been fixed shortly before Christmas: https://github.com/Raku/old-issue-tracker/issues/4902#issuecomment-570873862

Current output:
```
$ ./rakudo-m -e 'constant m = month'
===SORRY!=== Error while compiling -e
Undeclared routine:
    month used at line 1

```

There is also a test for the exception type in roast's S32-exceptions/misc.t, added with https://github.com/Raku/roast/commit/a4ace08538.

I'm closing this issue as resolved.
