### ISSUE TITLE
method delegation doesn't work in roles

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3721]
Migrated from [rt.perl.org#124007](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=124007) (status was 'open')

Searchable as RT124007$

**Comment by usev6** [comment]
This doesn't fail anymore:
```
$ ./rakudo-m -e 'role R { method foo () handles <bar> { say "alive" } }; R.foo'
alive
```

Tagging "testneeded".

**Comment by usev6** [comment]
I've added a test with https://github.com/Raku/roast/commit/91997f55b3.

Closing as "resolved".
