### ISSUE TITLE
org.perl6.nqp.runtime.UnwindException

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3777]
Migrated from [rt.perl.org#124279](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=124279) (status was 'new')

Searchable as RT124279$

**Comment by usev6** [comment]
I'm closing this old issue in favour of a new issue in the rakudo repo: https://github.com/rakudo/rakudo/issues/3634
