### ISSUE TITLE
uint32 behaving like int64

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3779]
Migrated from [rt.perl.org#124294](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=124294) (status was 'open')

Searchable as RT124294$

**Comment by usev6** [comment]
I assume these things are better now. @niner did some major rework for uint recently and the tests for this ticket (which were added to S02-types/native.t with https://github.com/Raku/roast/commit/08952f65f9) are passing now on MoarVM.

I'm closing this ticket now. (If there are remaining problems with uint64, we should open a new ticket over at https://github.com/rakudo/rakudo/issues.)
