### ISSUE TITLE
t/spec/S03-smartmatch/array-hash.t failes with "Type check failed"

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3801]
Migrated from [rt.perl.org#124444](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=124444) (status was 'open')

Searchable as RT124444$

**Comment by usev6** [comment]
The tests in question are working again -- unfudged with https://github.com/Raku/roast/commit/9df6e7a7d9.

I'm closing this issue as resolved.
