### ISSUE TITLE
NFC/NFG

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3841]
Migrated from [rt.perl.org#124500](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=124500) (status was 'open')

Searchable as RT124500$

**Comment by usev6** [comment]
I'll close this issue in favor of a [newly created issue in Rakudo's github repo](https://github.com/rakudo/rakudo/issues/4291).

(Rational: People looking for NGF support on the JVM backend usually don't search this repo.)
