### ISSUE TITLE
S02-types/array-shapes.t line:7 reason: 'array shapes'

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3842]
Migrated from [rt.perl.org#124502](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=124502) (status was 'open')

Searchable as RT124502$

**Comment by usev6** [comment]
I took a closer look at the two still failing tests today and I think they are wrong.

The tests were added to cover ```S09/Fixed-size arrays``` from the Synopsis back in 2008-07 with https://github.com/Raku/roast/commit/3547fffe14.

I wasn't able to track the synopsis document back to 2008-07, but on 2008-11-26 the relevant text looked like this (cmp. https://github.com/Raku/old-design-docs/blob/68d062fcaa/S09.pod?plain=1#L191-L195):

> Note that the square brackets are a compile-time declarator, not a run-time
> operator, so you can't use the "dotted" form either:
> 
>     my @values.[10];          # Error
>     my @keys\ .[10];          # Error

Only in 2010-09 the following clarification was done: https://github.com/Raku/old-design-docs/commit/e8527c2291
```
commit e8527c229122b5e2f8ae581f3716bc99a5fd3118
Author: Carl Masak <cmasak@gmail.com>
Date:   Wed Sep 29 07:51:17 2010 +0200

    [S09] be more clear about what's an error
    
    Two of the three examples marked with "Error" turned out to actually
    be logical maybe-not-what-I-meant errors. Marked them as such.

diff --git a/S09-data.pod b/S09-data.pod
index 0a4ba5d..fcad94d 100644
--- a/S09-data.pod
+++ b/S09-data.pod
@@ -207,8 +207,8 @@ specification, but "unspace" is allowed:
 Note that the square brackets are a compile-time declarator, not a run-time
 operator, so you can't use the "dotted" form either:
 
-    my @values.[10];          # Error
-    my @keys\ .[10];          # Error
+    my @values.[10];          # An indexing, not a fixed-size declaration
+    my @keys\ .[10];          # Ditto
 
 Attempting to access an index outside an array's defined range will fail:
```

And it looks like the code from the two tests indeed just does an indexing operation (calling ```&postcircumfix:<[ ]>``` on the freshly initialized array), e.g.
```
$ ./rakudo-m -e 'my @arr.[2] = 42; dd @arr'
Array @arr = [Any, Any, 42]
$ ./rakudo-m -e 'my @arr\ .[2] = 42; dd @arr'
Array @arr = [Any, Any, 42]
```
Those are not shaped arrays at all.

I'll make a PR for roast to adjust the tests.
*Edit*: PR exists now: https://github.com/Raku/roast/pull/841

**Comment by usev6** [comment]
I've merged the mentioned PR, so I'll close this issue as "resolved".
