### ISSUE TITLE
Failing tests in S06-other/main-usage.t: use of '--switch "arg1 arg2"' on command line

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3949]
Migrated from [rt.perl.org#124664](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=124664) (status was 'new')

Searchable as RT124664$

**Comment by usev6** [comment]
This has been resolved with https://github.com/rakudo/rakudo/pull/4209 (see also the discussion for the earlier version https://github.com/rakudo/rakudo/pull/4201).

The tests in roast's S06-other/main-usage.t have been reworked in https://github.com/Raku/roast/pull/716.

I'm closing this issue as resolved.
