### ISSUE TITLE
Roast rakudo skip/todo test:./S32-str/substr.t line:43 reason: 'java.nio.charset.MalformedInputException'

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#3970]
Migrated from [rt.perl.org#124692](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=124692) (status was 'open')

Searchable as RT124692$

**Comment by usev6** [comment]
I'm closing this old issue in favor of https://github.com/Raku/nqp/issues/783 (which refers to the concrete problem that still exists).
