### ISSUE TITLE
Roast rakudo skip/todo test:./S04-declarations/multiple.t line:30 reason: 'nom regression'

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4186]
Migrated from [rt.perl.org#125053](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=125053) (status was 'open')

Searchable as RT125053$

**Comment by lizmat** [comment]
I've seen another ticket today in which it was decided that this was **NOT** going to be supported.  So closing this ticket now.
