### ISSUE TITLE
Skipped tests in S32-list/map.t: "Too few positionals passed" when placeholder variables in map block get no value

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4232]
Migrated from [rt.perl.org#125146](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=125146) (status was 'new')

Searchable as RT125146$

**Comment by lizmat** [comment]
https://github.com/perl6/roast/commit/92fca54519ece3351265e93 changed the test to make sure that the signature of the block must always match the arguments given.  The auto-generating `$^a` syntax will *never* create optional parameters.  So the original tests were never going to pass.  The new test now codify the current behaviour.
