### ISSUE TITLE
CArray[num64] numiness optimised away

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4324]
Migrated from [rt.perl.org#125408](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=125408) (status was 'open')

Searchable as RT125408$

**Comment by usev6** [comment]
I see the test (t/04-nativecall/16-rt125408.t) passing on the JVM backend.

So I'm closing this as "fixed". (Hopefully there is no need to reopen again ;))
