### ISSUE TITLE
`loop { 0, .1 ... 1000 }` leaks memory

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4592]
Migrated from [rt.perl.org#126189](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126189) (status was 'open')

Searchable as RT126189$

**Comment by AlexDaniel** [comment]
I'm pretty sure that this is now resolved. I had it running for like an hour or so, and maxrss stabilized on 148916 KiB. That's of course very high, but it's what any script will reach, the code in question is not leaking any extra memory.

I tried both this:
```bash
perl6 -e 'loop { say 0, .1 ... 1000; use Telemetry; say T<max-rss> }'
```
And this:
```bash
perl6 -e 'loop { 0, .1 ... 1000; use Telemetry; say T<max-rss> }'
```
