### ISSUE TITLE
Unhandled exception: failed to load library 'dynext/libperl6_ops_moar.dylib'

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4682]
Migrated from [rt.perl.org#126473](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126473) (status was 'open')

Searchable as RT126473$

**Comment by usev6** [comment]
I stumbled upon this old issue. A lot of changes have been made to the build system in the last year and I'm pretty sure that the mentioned error doesn't happen anymore. (We'd probably have seen other reports.)

I'm going to close this issue.
