### ISSUE TITLE
Can't call HYPER, no signatures match

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4694]
Migrated from [rt.perl.org#126528](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126528) (status was 'open')

Searchable as RT126528$

**Comment by usev6** [comment]
The tests in S03-metaops/hyper.t are passing again (see https://github.com/perl6/roast/commit/f1c76c52d1), so I'm closing this issue.
