### ISSUE TITLE
>>~>> with a List of Pair on the left gets confused and starts talking about the Pairs being immutable in Rakudo

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4700]
Migrated from [rt.perl.org#126510](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126510) (status was 'new')

Searchable as RT126510$

**Comment by usev6** [comment]
There is no error anymore:
```
$ ./rakudo-m -e 'say (:a, :b, :c) >>~>> "foo"'
(a => Truefoo b => Truefoo c => Truefoo)
```

```bisectable6``` (https://colabti.org/irclogger/irclogger_log/raku-dev?date=2023-10-10#l85) points to https://github.com/rakudo/rakudo/commit/674a083705 for giving the current result.

I've created a PR for roast to add a test for this issue: https://github.com/Raku/roast/pull/844

**Comment by usev6** [comment]
I've merged the mentioned PR now. Closing as "resolved".
