### ISSUE TITLE
shouldn't be able to set defaults on native ints

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4703]
Migrated from [rt.perl.org#126519](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126519) (status was 'new')

Searchable as RT126519$

**Comment by usev6** [comment]
This test works now (cmp. https://github.com/Raku/roast/commit/b0eda67335).

I don't know when/how it was fixed, but I'll close this old ticket.
