### ISSUE TITLE
Single named match does not work with hyper (».Str)

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4715]
Migrated from [rt.perl.org#126574](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126574) (status was 'open')

Searchable as RT126574$

**Comment by raiph** [comment]
The filer's title is misleading. It's not about named matches. The same issue arises with *positional* matches:
```
grammar G {rule TOP { (A) } }
my $g = G.parse("A");
say $g[0].Str;  # A
say $g[0]».Str; # ()
```
The filer's confusion/expectation was that a hyper would/should fall back to treating a capture as a list of that capture if it had no (positional) *sub* captures. I can see why, but such a fallback would be awful.

This might arguably belong as a doc issue, but I don't think so, so I'm not going to file one.
