### ISSUE TITLE
--target=ast generating error or warning

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4801]
Migrated from [rt.perl.org#126764](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=126764) (status was 'new')

Searchable as RT126764$

**Comment by usev6** [comment]
The two commands don't generate an error or warning anymore.

Since this is a very old issue (even pre Christmas), I'll close it now.
(I don't think we need a regression test. Please reopen if you disagree.)
