### ISSUE TITLE
Install scripts don't respect DESTDIR

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4932]
Migrated from [rt.perl.org#127032](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=127032) (status was 'open')

Searchable as RT127032$

**Comment by usev6** [comment]
I'm closing this very old issue about rakudo-2015.12 now. I'm pretty sure that installing Rakudo using ```--prefix``` works nowadays. (If not we'd need a new issue over at https://github.com/rakudo/rakudo or https://github.com/rakudo/star.)
