### ISSUE TITLE
Installation of rakudo-2015.12 fails

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4941]
Migrated from [rt.perl.org#127040](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=127040) (status was 'open')

Searchable as RT127040$

**Comment by usev6** [comment]
This is a very old issue about rakudo-2015.12. I'm pretty sure that installing Rakudo using ```--prefix``` works nowadays. (If not we'd need a new issue over at https://github.com/rakudo/rakudo or https://github.com/rakudo/star.) I'm closing this issue.

(Just as a note: The mentioned patch for NPQ has been applied back in 2015-03 (with modified variable names): https://github.com/Raku/nqp/commit/d24d3872d7.)
