### ISSUE TITLE
Tests fail when contained in one file, pass when separated (2015.12 Regression from 2015.11)

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#4944]
Migrated from [rt.perl.org#127046](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=127046) (status was 'new')

Searchable as RT127046$

**Comment by usev6** [comment]
Unfortunately no-one found the time to look into this issue when it was fresh. Now, the links to the actual test code don't work anymore. I'll close the issue as "stale"/"can't reproduce".
