### ISSUE TITLE
Cannot build on Alpine Linux

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5002]
Migrated from [rt.perl.org#127173](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=127173) (status was 'open')

Searchable as RT127173$

**Comment by usev6** [comment]
Even though I didn't try to build on Alpine Linux, I'm pretty sure that it works fine nowadays. (There is, for instance, https://github.com/JJ/alpine-raku which is based on Alpine Linux.)

In any case I don't think that looking further into this old issue will bring any benifit. Therefore I'm closing it (as resolved).
