### ISSUE TITLE
uint behaves like signed int in CUnion

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5022]
Migrated from [rt.perl.org#127210](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=127210) (status was 'open')

Searchable as RT127210$

**Comment by niner** [comment]
Fixed as of https://github.com/rakudo/rakudo/commit/8bba2aec43c14ad9a2ce5a00d2333b46cad30c14
