### ISSUE TITLE
error message when using commas in c-style “loop” (loop (my $x = 0, $x < 10, $x++) {})

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5220]
Migrated from [rt.perl.org#127857](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=127857) (status was 'new')

Searchable as RT127857$

**Comment by AlexDaniel** [comment]
Closing as https://github.com/rakudo/rakudo/pull/1188 was merged.
