### ISSUE TITLE
Mu methods cannot be used as grammar tokens due to default Actions class

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5247]
Migrated from [rt.perl.org#127945](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=127945) (status was 'open')

Searchable as RT127945$

**Comment by raiph** [comment]
I didn't mean to close this. Fat fingers. That said, I think that the fix to the issue I just mentioned this in means this issue may, hopefully will, be closed.

**Comment by codesections** [comment]
Fixed in https://github.com/Raku/roast/commit/31115d7f21b236a65441e9bd04b2a71b49ac837e
