### ISSUE TITLE
https://rakudo.org doesn't work, http://rakudo.org/ does

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5387]
Migrated from [rt.perl.org#128423](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=128423) (status was 'new')

Searchable as RT128423$

**Comment by usev6** [comment]
This has definitely been fixed over the last couple of years. https://rakudo.org has a certificate from Cloudflare nowadays with the following Subject Alt Names:
* sni.cloudflaressl.com
* rakudo.org
* *.rakudo.org

I'm closing this issue.
