### ISSUE TITLE
Proc.exitcode is zero for processes killed by signals

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5512]
Migrated from [rt.perl.org#128805](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=128805) (status was 'open')

Searchable as RT128805$

**Comment by AlexDaniel** [comment]
This was fixed in (2019-09-05) https://github.com/rakudo/rakudo/commit/225b1c56f96f290f4df4804ab95edeeda445227e, a dup ticket is here: https://github.com/rakudo/rakudo/issues/3149
