### ISSUE TITLE
handles runs after role stub required method checking

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5687]
Migrated from [rt.perl.org#129325](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=129325) (status was 'new')

Searchable as RT129325$

**Comment by usev6** [comment]
This looks very similar to the problem reported in https://github.com/rakudo/rakudo/issues/2386. There is an extra class in this issue, but it doesn't seem to be relevant for the bug.

The code works nowadays:
```
$ ./rakudo-m -e 'role R { method f {...} }; class A { method f { } }; class B does R { has A $.a handles <f> }; say "alive"'
alive
```

According to [commitable](https://colabti.org/irclogger/irclogger_log/raku-dev?date=2023-02-19#l173) it has been fixed between 2018.09 and 2018.10 -- so I'm sure it was the fix from https://github.com/rakudo/rakudo/issues/2386.

> 21:08 < bartolin_> c: 2018.09 role R { method f {...} }; class A { method f { } }; class B does R { has A $.a handles <f> } ## https://github.com/Raku/old-issue-tracker/issues/5687
> 21:08 < committable6> bartolin_, ¦2018.09: «===SORRY!=== Error while compiling /tmp/r7RcbT9aiB␤Method 'f' must be implemented by B because it is required by roles: R.␤at /tmp/r7RcbT9aiB:1␤ «exit code = 1»»
> 21:09 < bartolin_> c: 2018.10 role R { method f {...} }; class A { method f { } }; class B does R { has A $.a handles <f> } ## https://github.com/Raku/old-issue-tracker/issues/5687
> 21:09 < committable6> bartolin_, ¦2018.10: «»

I'd say that the test added to roast with https://github.com/Raku/roast/commit/f3dec0b3c9 covers this issue as well.
So I'll close this as "resolved". (Please reopen if you think this needs a dedicated test.)
