### ISSUE TITLE
Coercion type in variable declarations

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5853]
Migrated from [rt.perl.org#130253](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=130253) (status was 'open')

Searchable as RT130253$

**Comment by usev6** [comment]
This has been implemented by @vrurg in the context of https://github.com/Raku/problem-solving/issues/227. The example from above works now:
```
$ ./rakudo-m -e 'my Int(Cool) $x; $x = "42"; dd $x'
Int $x = 42
```

Tests have been added with https://github.com/Raku/roast/pull/674, so I'm closing this issue.
