### ISSUE TITLE
NativeCall: CArray[uint8] may contain negative numbers

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5859]
Migrated from [rt.perl.org#130267](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=130267) (status was 'open')

Searchable as RT130267$

**Comment by zhuomingliang** [comment]
Could be closed by https://github.com/rakudo/rakudo/commit/ac009507a2?

**Comment by lizmat** [comment]
@zhuomingliang Indeed, thanks for noticing!
