### ISSUE TITLE
rakudo star 2016-11 with jvm fails in debian 8 with java 64bit

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5903]
Migrated from [rt.perl.org#130387](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=130387) (status was 'new')

Searchable as RT130387$

**Comment by usev6** [comment]
I'm afraid, it's still not possible to use rakudo star on the JVM backend. The current problem is that https://github.com/ugexe/zef (which has replaced panda for module management) doesn't work on the JVM backend. There is at last one open issue with the JVM backend that prevents Zef from running correctly: https://github.com/rakudo/rakudo/issues/3790

However, I don't think it makes sense to keep this particular issue open:
* Debian 8 is no longer supported
* Java 8 is no longer supported
* panda is no longer in use
* the old bug tracker is no longer in use
