### ISSUE TITLE
panda 2016.11 install failed on Windows

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5905]
Migrated from [rt.perl.org#130391](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=130391) (status was 'open')

Searchable as RT130391$

**Comment by usev6** [comment]
Since neither panda (replaced by [Zef](https://github.com/ugexe/zef)) nor Windows 7 are supported anymore, I'm closing this issue.
