### ISSUE TITLE
No link to the ticket in an automatic response after submitting a bug report

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5908]
Migrated from [rt.perl.org#130399](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=130399) (status was 'open')

Searchable as RT130399$

**Comment by usev6** [comment]
Since RT is no longer used for Rakudo bugs, I'll close this issue. (Nowadays Rakudo bugs are tracked at https://github.com/rakudo/rakudo/issues.)
