### ISSUE TITLE
cannot subclass Proxy

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5911]
Migrated from [rt.perl.org#130403](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=130403) (status was 'new')

Searchable as RT130403$

**Comment by JJ** [comment]
I'm afraid that link has disappeared. I'll try to look it up in archive.org.

**Comment by JJ** [comment]
It does not exist. So unless @FCO remembers what this is about, probably closing it.

**Comment by FCO** [comment]
I don’t :(

**Comment by JJ** [comment]
Maybe replicate the example? Should be as easy as 

```
class Proxier is Proxy {}; say Proxier.new.raku
```

Although in this case subclassing work; `.new` does not. Closing it, unless someone finds another interpretation for the OP.
