### ISSUE TITLE
Hyper method call of AT-KEY/AT-POS fails with empty arrays (my @x; say @x»[0])

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#5978]
Migrated from [rt.perl.org#130503](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=130503) (status was 'new')

Searchable as RT130503$

**Comment by raiph** [comment]
Works in a recent Rakudo:
```
say $*RAKU;        # Raku (6.d)
my @x; say @x»[0]; # ()
```
