### ISSUE TITLE
Problems with 'with' and attached block

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6070]
Migrated from [rt.perl.org#130775](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=130775) (status was 'new')

Searchable as RT130775$

**Comment by usev6** [comment]
Just some more context:

* implementation for MoarVM: https://github.com/Raku/nqp/commit/4de65a56d6
* (incomplete) implementation for JVM (to unbreak build): https://github.com/perl6/nqp/commit/a8c8ee4ff6
* Some conversation between jnthn and timtoady about code-gen for with/without: https://colabti.org/irclogger/irclogger_log/perl6?date=2015-08-07#l1229

**Comment by usev6** [comment]
The problem has been fixed with https://github.com/Raku/nqp/pull/734.

I've unfudged the tests in roast with https://github.com/Raku/roast/commit/f7810e8018.
