### ISSUE TITLE
Cannot initialize object hashes with coercive types

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6176]
Migrated from [rt.perl.org#131103](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=131103) (status was 'new')

Searchable as RT131103$

**Comment by usev6** [comment]
This seems to work now.
```
$ ./rakudo-m -e 'my %h{Str(Cool)} = a => 42; say %h<a>'
42
$ ./rakudo-m -e 'my %h{Int(Str)} = "10" => 42; say %h.keys[0].^name'
Int
```

Tagging as testneeded.

**Comment by usev6** [comment]
According to ```bisectable6``` (https://colabti.org/irclogger/irclogger_log/raku-dev?date=2023-10-21#l50) this seems to work since https://github.com/rakudo/rakudo/commit/f2d73287f9.

Test added with https://github.com/Raku/roast/commit/1f824745f2.

Closing as "resolved".
