### ISSUE TITLE
unsigned native ints not applied in class attributes

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6184]
Migrated from [rt.perl.org#131122](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=131122) (status was 'open')

Searchable as RT131122$

**Comment by niner** [comment]
Fixed as of https://github.com/rakudo/rakudo/commit/8bba2aec43c14ad9a2ce5a00d2333b46cad30c14
