### ISSUE TITLE
FreeBSD 11, rakudo r5e74017d: fails test 11 in t/04-nativecall/02-simple-args.t

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6210]
Migrated from [rt.perl.org#131237](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=131237) (status was 'new')

Searchable as RT131237$

**Comment by usev6** [comment]
I've found this issue in Rakudo's current bug tracker: https://github.com/rakudo/rakudo/issues/1619

That issue has a lot more information. But basically it indeed looks like a problem specific to clang.

I'll close this issue in favor of the other one.
