### ISSUE TITLE
Wrong rakudo's INSTALL.txt instructions mention non-existent --with-moar option

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6392]
Migrated from [rt.perl.org#131745](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=131745) (status was 'new')

Searchable as RT131745$

**Comment by usev6** [comment]
The reference to ```--with-moar``` has been removed back in 2020 with https://github.com/rakudo/rakudo/commit/8bb0235bb0.

Closing as "resolved".
