### ISSUE TITLE
'Unhandled exception: const_n32 NYI at SeekFromEnd:9154'

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6396]
Migrated from [rt.perl.org#131758](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=131758) (status was 'open')

Searchable as RT131758$

**Comment by AlexDaniel** [comment]
Thanks for reporting! Looks like there was some fix applied, and I don't remember anybody else reporting the same problem. So I'd consider this fixed. Writing a test in this case is not trivial, so perhaps we're better off just calling it resolved and closing the ticket. Thanks @timo!
