### ISSUE TITLE
better error message for exit("hello")

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6438]
Migrated from [rt.perl.org#131877](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=131877) (status was 'open')

Searchable as RT131877$

**Comment by JJ** [comment]
I think this could be closed. The error issued is consistent with the behavior. If  no one is against, I'll close it in a few days/hours.

**Comment by toolforger** [comment]
+1

**Comment by JJ** [comment]
Closing it then. Thanks!
