### ISSUE TITLE
Zen/Whatever slice ignore :v

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6465]
Migrated from [rt.perl.org#131956](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=131956) (status was 'open')

Searchable as RT131956$

**Comment by JJ** [comment]
`:v` does too now:

```shell
> raku -e  'my @a = ^5; @a[10]=42; .say for @a[]:v'
0
1
2
3
4
42
```
