### ISSUE TITLE
‘make test’ does not work before ‘make install’

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6524]
Migrated from [rt.perl.org#132101](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=132101) (status was 'open')

Searchable as RT132101$

**Comment by usev6** [comment]
This is actually no longer a problem: ```make test``` can be used before ```make install``` on the JVM backend (see the linked issue in Rakudo's current bug tracker).

A different problem is, that ```make test``` is very slow and that there are two or three failing tests. But that's outside the scope of this issue, so I'm closing here.
