### ISSUE TITLE
require ‘’ suggests ‘.’ but that makes no sense (require ‘’)

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6588]
Migrated from [rt.perl.org#132250](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=132250) (status was 'new')

Searchable as RT132250$

**Comment by p6rt** [comment]
### From @AlexDaniel

Code&#8203;:
require ""

Result&#8203;:
Must specify something as a path&#8203;: did you mean '\.' for the current directory?
&nbsp;  in block \<unit> at \-e line 1


I don't think you can require a directoryâ½

The error message comes from here https://github.com/rakudo/rakudo/blob/d565ded0292813582a285835b4a388279ca8c6a3/src/core/IO/Path.pm#L15
and has nothing to do with ï½¢requireï½£\.

**Comment by JJ** [comment]
I'm not totally sure it makes sense for  any kind of file, either.

```raku
say ("").IO # Must specify something as a path: did you mean '.' for the current directory?
```
