### ISSUE TITLE
=begin comment/=end comment blocks ought to nest

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6653]
Migrated from [rt.perl.org#132650](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=132650) (status was 'new')

Searchable as RT132650$

**Comment by JJ** [comment]
@tbrowder is this in the spec? Or just a wishlist?

**Comment by tbrowder** [comment]
I'll have to look again at the speculations, but it would be very useful.  I may have to ask Damian.

**Comment by tbrowder** [comment]
Ugh, gonna close this. Don't know what I was thinking. Definitely should be closed. Happy New Year!

**Comment by JJ** [comment]
Happy new year!
