### ISSUE TITLE
Quanthashes should be parameterizable

### ISSUE THREAD

**Issue by p6rt** [Raku/old-issue-tracker#6689]
Migrated from [rt.perl.org#133762](https://rt-archive.perl.org/perl6/Ticket/Display.html?id=133762) (status was 'open')

Searchable as RT133762$

**Comment by JJ** [comment]
I would say this is fixed? All possible QuantHashes have been fixed.

**Comment by lizmat** [comment]
Indeed.  But I think it may still need tests?

**Comment by lizmat** [comment]
Tests added with https://github.com/Raku/roast/commit/fa99dd67b2
